"""
Python script to generate a yaml meta data file from a parquet file.
"""

import datetime
from dataclasses import dataclass
from pathlib import Path
import polars as pl

from pymaml.maml import MAMLBuilder

from .WAVES_config import ANSI, ColumnMetaData
from .metadata_generator import fields_from_lf


@dataclass
class Skeleton:
    """
    Skeletal structure of what is expected in a maml file.
    """

    table: str
    fields: list[ColumnMetaData]
    date: str = str(datetime.datetime.today()).split(" ")[0]
    license: str = "Copyright WAVES [Private]"

    def to_file(self, outfile: Path) -> None:
        builder = MAMLBuilder("v1.1")
        builder.set("dataset", "--")
        builder.set("date", self.date)
        builder.set("MAML_version", "1.1")
        builder.set("table", self.table)
        builder.set("version", "--")
        builder.set("author", "--")
        for column in self.fields:
            builder.add("fields", column.to_maml_dict())

        maml = builder.build()
        maml.to_file(str(outfile), include_none=True)
        _clean_file(outfile)


def _clean_file(file_name: Path) -> None:
    """
    Cleans the outputed maml file to produce a skeletal structure for WAVES specific MAML.

    Removes any place holder values for required fields, and cleans up non accepted fields.
    """
    with open(file_name) as file:
        lines = file.readlines()
    lines = [line.replace("--", "") for line in lines]
    forbidden_words = ["array_size:", "keyarray:", "extra:", "miss:"]
    for forbidden_word in forbidden_words:
        lines = [line for line in lines if forbidden_word not in line]
    good_lines = []
    for i, line in enumerate(lines):
        if line.strip()[:3] == "qc:":
            try:
                if lines[i + 1].strip()[:3] == "min":
                    good_lines.append(line)
            except IndexError:
                pass
        else:
            good_lines.append(line)

    with open(file_name, "w") as file:
        file.write(
            "# Autogenerated maml. Please see https://waves.wiki.org.au/en/Working-Groups/TWG7-WAVES-database/WAVES-metadata-format-MAML to understand the waves maml format. This comment can be deleted.\n"
        )
        file.writelines(good_lines)


def _allowed_to_overwrite(file_name: Path) -> bool:
    """Helper function to handle the looping logic for user input."""
    responses = {
        "y": True,
        "yes": True,
        "yeah": True,
        "yup": True,
        "n": False,
        "no": False,
        "nope": False,
        "nah": False,
    }
    if file_name.is_file():
        can_write = input(
            f"File '{file_name}' already exists. Some fields might be lost. Do you wish to overwrite. (y/n): "
        )
        while can_write not in responses:
            can_write = input(
                "\nThat isn't a valid response. Please type 'y' for yes or 'n' for no: "
            )
        return responses[can_write]
    else:  # If the file doesn't exist just write it.
        return True


def make_maml(file_name: Path) -> None:
    """
    Creates the maml file from the .parquet file
    """
    df = pl.scan_parquet(file_name)
    fields = fields_from_lf(df)
    if not fields:
        print(
            f"{ANSI.RED}{ANSI.BOLD}The parquet file '{file_name}' seems empty. MAML can not be built.{ANSI.RESET}"
        )
    else:
        out_filename = file_name.with_suffix(".maml")
        if _allowed_to_overwrite(out_filename):
            basic_maml = Skeleton(file_name.stem, fields)
            basic_maml.to_file(out_filename)
            print(f"{ANSI.BOLD}MAML file written to '{out_filename}'.{ANSI.RESET}")
